name: Master-Script-Workflow
on:
  push:
    branches:
      - 'QA'
  pull_request:
    branches:
      - 'QA'

jobs:
  Create-Final-Master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Master Script
        run: |
          RELEASE_DIR="RELEASE_SCRIPTS"
          SPRINT_FOLDER="${{ vars.SPRINT_NAME }}"
          MASTER_PATH="$RELEASE_DIR/$SPRINT_FOLDER/DDL_CONSOLIDATED.sql"
          BASE_ADHOC="$RELEASE_DIR/$SPRINT_FOLDER/Adhoc_Scripts.sql"
          GRANTS_FILE="$RELEASE_DIR/$SPRINT_FOLDER/Grants.sql"

          rm -f "$MASTER_PATH"

          if [ -f "$BASE_ADHOC" ]; then
            echo "-- BASELINE FROM ADHOC_SCRIPT.SQL --" > "$MASTER_PATH"
            cat "$BASE_ADHOC" >> "$MASTER_PATH"
          else
            echo "-- START OF MASTER SCRIPT --" > "$MASTER_PATH"
          fi

           if [ "${{ github.event_name }}" == "pull_request" ]; then
            CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD -- \
            'DBO_SCHEMA/Views/*.sql' \
            'BI_WINGSPAN_ANALYTICS/*.sql' \
            'STG_WINGSPAN_ANALYTICS/*.sql' \
            'CERTIFIED_BUSINESS_WINGSPAN_ANALYTICS/*.sql' || true)
          else
            CHANGED_FILES=$(git diff --name-only HEAD^ HEAD -- \
            'DBO_SCHEMA/Views/*.sql' \
            'BI_WINGSPAN_ANALYTICS/*.sql' \
            'STG_WINGSPAN_ANALYTICS/*.sql' \
            'CERTIFIED_BUSINESS_WINGSPAN_ANALYTICS/*.sql' || true)
          fi

          if [ -n "$CHANGED_FILES" ]; then
            echo -e "\n-- MERGED CONTENT START --\n" >> "$MASTER_PATH"
            for file in $CHANGED_FILES; do
              if [ -f "$file" ]; then
                echo -e "-- Source: $file --" >> "$MASTER_PATH"
                cat "$file" >> "$MASTER_PATH"
                echo -e "\n" >> "$MASTER_PATH"
              fi
            done
          fi

          if [ -f "$GRANTS_FILE" ]; then
            echo -e "-- GRANTS START --" >> "$MASTER_PATH"
            cat "$GRANTS_FILE" >> "$MASTER_PATH"
          fi

      - name: Push changes
        if: github.event_name == 'push'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update DDL_CONSOLIDATED.sql [skip ci]" || exit 0
          # This pushes to the specific branch that triggered the action
          git push origin HEAD:${{ github.ref_name }}



