name: Master-Script-On-Merge
on:
  push:
    branches:
      - 'main'

jobs:
  Create-Final-Master:
    # This condition ensures it only runs if the push was a PR merge
    if: github.event.head_commit.message != '' 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Essential to see previous commits for the diff

      - name: Generate Master Script
        run: |
          # 1. Setup paths
          RELEASE_DIR="RELEASE_SCRIPTS"
          SPRINT_FOLDER="Sprint_160"
          MASTER_PATH="$RELEASE_DIR/$SPRINT_FOLDER/DDL_CONSOLIDATED.sql"
          BASE_ADHOC="$RELEASE_DIR/$SPRINT_FOLDER/Adhoc_script.sql"
          GRANTS_FILE="$RELEASE_DIR/$SPRINT_FOLDER/GRANTS.sql"

          
          rm -f "$MASTER_PATH"

          # 2. Add Adhoc Script first (if exists)
          if [ -f "$BASE_ADHOC" ]; then
            echo "-- BASELINE FROM ADHOC_SCRIPT.SQL --" > "$MASTER_PATH"
            cat "$BASE_ADHOC" >> "$MASTER_PATH"
          else
            echo "-- START OF MASTER SCRIPT --" > "$MASTER_PATH"
          fi

          # 3. Add changed SQL files (exclude the release directory itself)
          CHANGED_FILES=$(git diff --name-only --diff-filter=ACMR HEAD^ HEAD -- '*.sql' ":!RELEASE_SCRIPTS/*" ':!DBO_SCHEMA/*' ':!STG_HIST_SCHEMA/*' ':!AUDIT_SCHEMA/*' || true)

          if [ -n "$CHANGED_FILES" ]; then
            echo -e "\n-- MERGED CONTENT START --\n" >> "$MASTER_PATH"
            for file in $CHANGED_FILES; do
              if [ -f "$file" ]; then
                echo -e "-- Source: $file --" >> "$MASTER_PATH"
                cat "$file" >> "$MASTER_PATH"
                echo -e "\n" >> "$MASTER_PATH"
              fi
            done
          fi

          # 4. Add Grants Script last (if exists)
          if [ -f "$GRANTS_FILE" ]; then
            echo -e "-- GRANTS START --" >> "$MASTER_PATH"
            cat "$GRANTS_FILE" >> "$MASTER_PATH"
          fi

          # 5. Push changes
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "$MASTER_PATH"
          git commit -m "Update DDL_CONSOLIDATED.sql [skip ci]" || exit 0
          git push origin main

